version: "3.9"
services:
  app:
    build:
      context: ./app
    container_name: app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./facilities.db:/app/facilities.db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-ssl:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-ssl:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  certbot-ssl: