version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app/facilities.db:/app/facilities.db
    networks:
      webnet:
        ipv4_address: 172.18.0.10

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"