version: "3.9"
services:
  app:
    build:
      context: ./app
    container_name: app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./facilities.db:/app/facilities.db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-ssl:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot  # Папка для webroot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-ssl:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot  # Папка для webroot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 2073600; done"  # Для поддержки webroot

volumes:
  certbot-ssl: